services:
  - type: web
    name: tripcanvas-site
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /privacy-policy
        destination: /privacy-policy/index.html
      - type: rewrite
        source: /terms-of-service
        destination: /terms-of-service/index.html
      - type: rewrite
        source: /*
        destination: /index.html
